CREATE DATABASE [ShoesApplicationDatabase]

GO

USE [ShoesApplicationDatabase]

GO

--Problem 01
CREATE TABLE [Users](
	[Id] INT PRIMARY KEY IDENTITY,
	[Username] NVARCHAR(50) UNIQUE NOT NULL,
	[FullName] NVARCHAR(100) NOT NULL,
	[PhoneNumber] NVARCHAR(15),
	[Email] NVARCHAR(100) UNIQUE NOT NULL
)

CREATE TABLE [Brands](
	[Id] INT PRIMARY KEY IDENTITY,
	[Name] NVARCHAR(50) UNIQUE NOT NULL
)

CREATE TABLE [Sizes](
	[Id] INT PRIMARY KEY IDENTITY,
	[EU] DECIMAL(5,2) NOT NULL,
	[US] DECIMAL(5,2) NOT NULL,
	[UK] DECIMAL(5,2) NOT NULL,
	[CM] DECIMAL(5,2) NOT NULL,
	[IN] DECIMAL(5,2) NOT NULL
)

CREATE TABLE [Shoes](
	[Id] INT PRIMARY KEY IDENTITY,
	[Model] NVARCHAR(30) NOT NULL,
	[Price] DECIMAL(10, 2) NOT NULL,
	[BrandId] INT FOREIGN KEY REFERENCES [Brands]([Id]) NOT NULL
)

CREATE TABLE [Orders](
	[Id] INT PRIMARY KEY IDENTITY,
	[ShoeId] INT FOREIGN KEY REFERENCES [Shoes]([Id]) NOT NULL,
	[SizeId] INT FOREIGN KEY REFERENCES [Sizes]([Id]) NOT NULL,
	[UserId] INT FOREIGN KEY REFERENCES [Users]([Id]) NOT NULL
)

CREATE TABLE [ShoesSizes](
	[ShoeId] INT FOREIGN KEY REFERENCES [Shoes]([Id]) NOT NULL,
	[SizeId] INT FOREIGN KEY REFERENCES [Sizes]([Id]) NOT NULL,
	PRIMARY KEY ([ShoeId], [SizeId])
)

